### ISSUE TITLE
[QUESTION] How can nestjs-roles be used together with AuthGuard? No user found on request object.

### ISSUE THREAD

**Issue by heivoll** [iamolegga/nestjs-roles#474]
[X] I've read [the docs](https://github.com/iamolegga/nestjs-roles/blob/master/README.md)

[X] I couldn't find the same [question](https://github.com/iamolegga/nestjs-roles/issues?q=is%3Aissue+label%3Aquestion)

**Question**

I've set up nestjs-roles with a getRole function that looks for a user property on the request object. This user is set by the AuthGuard (using Passport with a JWT Strategy). However, it appears that whenever I've applied the Roles guard to an endpoint or controller, the AuthGuard is not run (not reaching the validate method), so the user property is never on the session object, ending up in a 401.

Is there a way of having both these run on the same endpoints? I've tried with 

```
@UseGuards(AuthGuard())
@RolesGuard.Params(Role.SUPERADMIN)
```

as decorators.

Any help would be greatly appreciated!

**Comment by iamolegga** [comment]
Could you add some minimal repo example to play with?

**Comment by heivoll** [comment]
@iamolegga Bah, figured it out. I'd followed the docs for the initial setup and forgot that I added `app.useGlobalGuards(new RolesGuard(reflector));` in main.ts, which then apparently is not overriden by setting @UseGuards on the controller or endpoint later. So just removing that line fixed the issue. D'oh! Sorry for the time wasted.

**Comment by iamolegga** [comment]
Hm, but roles guard should not work without setting via `app.useGlobalGuards` 😀

**Comment by heivoll** [comment]
You're right. It was rather that I had to also add the passport AuthGuard as a global guard as well for it to work. Basically just adding
```
 {
      provide: APP_GUARD,
      useClass: AuthGuard(['jwt', 'anonymous']),
    },
```
to providers in app.module.ts (in my setup), so it's used everywhere and adds the user object to the request.
