### ISSUE TITLE
[QUESTION] Array of roles

### ISSUE THREAD

**Issue by fiqrisr** [iamolegga/nestjs-roles#554]
[x] I've read [the docs](https://github.com/iamolegga/nestjs-roles/blob/master/README.md)

[x] I couldn't find the same [question](https://github.com/iamolegga/nestjs-roles/issues?q=is%3Aissue+label%3Aquestion)

**Question**
How to make it work with array of roles? For example, I have two roles, admin and user. A user can have multiple roles. I want to make it works like this: 
```ts
function getRole(context: ExecutionContext) {
  const request = context.switchToHttp().getRequest();
  const jwtToken = jwt_decode(request.headers.authorization);

  return jwtToken['roles']; // array of roles
}

export const RoleGuard = createRolesGuard<Role>(getRole);
```
For now the library does not work if I pass it with array of roles.

Thanks and sorry for my bad English.

**Comment by iamolegga** [comment]
fill free to add pr with extra check for array, I'll try to merge it asap. PS: don't forget to add tests and docs (if required)

**Comment by fiqrisr** [comment]
> fill free to add pr with extra check for array, I'll try to merge it asap. PS: don't forget to add tests and docs (if required)

Here #555
